spring:
  application:
    name: spring-lab

server:
  port: 8080

app:
  owner: Sansyzbay Inzhu
  group: IT1-2413IS
  mail:
    from: no-reply@iitu.kz
    retry-count: 3
    timeout: 5s
    enabled: true

logging:
  level:
    kz.iitu: INFO

# Добавлено для Task 5 (Actuator)
management:
  endpoints:
    web:
      exposure:
        include: health,env,configprops,conditions